In [1]:
import yfinance as yf
import datetime
import os

start_date = "2020-01-01"
end_date = datetime.datetime.today().strftime('%Y-%m-%d')

ticker = yf.Ticker("^GSPC")  # ^GSPC traks S&P 500 while QQQ tracks NASDAQ-100
sp500 = ticker.history(start=start_date, end=end_date)

os.makedirs("data/raw", exist_ok=True) # Ensure the data/ folder exists

In [2]:
sp500.tail(10)  # Show first few rows

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2025-05-29 00:00:00-04:00,5939.959961,5943.129883,5873.799805,5912.169922,4569750000,0.0,0.0
2025-05-30 00:00:00-04:00,5903.669922,5922.140137,5843.660156,5911.689941,6378540000,0.0,0.0
2025-06-02 00:00:00-04:00,5896.680176,5937.399902,5861.430176,5935.939941,4832240000,0.0,0.0
2025-06-03 00:00:00-04:00,5938.560059,5981.350098,5929.000000,5970.370117,5026680000,0.0,0.0
2025-06-04 00:00:00-04:00,5978.939941,5990.479980,5966.109863,5970.810059,4767050000,0.0,0.0
2025-06-05 00:00:00-04:00,5985.669922,5999.700195,5921.200195,5939.299805,5091850000,0.0,0.0
2025-06-06 00:00:00-04:00,5987.060059,6016.870117,5978.629883,6000.359863,4355710000,0.0,0.0
2025-06-09 00:00:00-04:00,6004.629883,6021.310059,5994.180176,6005.879883,4642360000,0.0,0.0
2025-06-10 00:00:00-04:00,6009.910156,6043.009766,6000.279785,6038.810059,4882880000,0.0,0.0
2025-06-11 00:00:00-04:00,6049.379883,6059.399902,6002.319824,6022.240234,5111550000,0.0,0.0

In [3]:
sp500.to_csv("data/raw/sp500.csv", index=True)